apiVersion: apps/v1

kind: Deployment

metadata:
  name: todo-ms-deployment
  labels:
    name: todo-ms-deployment
    app: demo-app
    
spec:
  replicas: 1
 
    
  selector:
    matchLabels:
      name: todo-ms-pod
      app: demo-app
    
  template:
    metadata:
      name: todo-ms-pod
      labels:
        name: todo-ms-pod
        app: demo-app
  
    spec:
      containers:
        - name: task-app
          image: subhghosh/todoapp
          ports:
            - containerPort: 9080
   
  