apiVersion: v1
kind: Service

metadata:
  name: todo-ms-service
  labels:
    name: todo-ms-service
    app: demo-app

spec:
  ports:
  - port: 9080
    targetPort: 9080
  type: LoadBalancer

  selector:
    name: todo-ms-pod
    app: demo-app
     

