apiVersion: v1
kind: Pod
metadata:
  name: hello-pod
  labels:
    name: hello-pod
    app: demo-app 
spec:
  containers:
    - name: hello-app
      image: subhghosh/dockerkubs
      ports:
        - containerPort: 8080
