apiVersion: v1
kind: Service
metadata:
  name: hello-service
  labels:
    name: hello-service
    app: demo-app
spec:
  ports:
  - port: 8080
    targetPort: 8080
  type: LoadBalancer

  selector:
    name: hello-pod
    
    app: demo-app
     

